{
  "cve": {
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
      "ID": "CVE-2019-3498",
      "ASSIGNER": "cve@mitre.org"
    },
    "affects": {
      "vendor": {
        "vendor_data": [

        ]
      }
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [

          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "url": "http://www.securityfocus.com/bid/106453",
          "name": "106453",
          "refsource": "BID",
          "tags": [

          ]
        },
        {
          "url": "https://docs.djangoproject.com/en/dev/releases/security/",
          "name": "https://docs.djangoproject.com/en/dev/releases/security/",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ",
          "name": "https://groups.google.com/forum/#!topic/django-announce/VYU7xQQTEPQ",
          "refsource": "MISC",
          "tags": [

          ]
        },
        {
          "url": "https://lists.debian.org/debian-lts-announce/2019/01/msg00005.html",
          "name": "[debian-lts-announce] 20190106 [SECURITY] [DLA 1629-1] python-django security update",
          "refsource": "MLIST",
          "tags": [

          ]
        },
        {
          "url": "https://usn.ubuntu.com/3851-1/",
          "name": "USN-3851-1",
          "refsource": "UBUNTU",
          "tags": [

          ]
        },
        {
          "url": "https://www.debian.org/security/2019/dsa-4363",
          "name": "DSA-4363",
          "refsource": "DEBIAN",
          "tags": [

          ]
        },
        {
          "url": "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/",
          "name": "https://www.djangoproject.com/weblog/2019/jan/04/security-releases/",
          "refsource": "MISC",
          "tags": [

          ]
        }
      ]
    },
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content."
        }
      ]
    }
  },
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [

    ]
  },
  "impact": {
  },
  "publishedDate": "2019-01-09T23:29Z",
  "lastModifiedDate": "2019-01-10T11:29Z"
}